" Force Vim settings, rather than Vi settings. This has to come first.
set nocompatible

" ========== General Config =========
set number
syntax on
set backspace=indent,eol,start

set history=1000
set showcmd
set showmode

set hidden "Allow buffers to exist in background without being in a window


let mapleader = "," "Set leader key before loading plugins

" ========== Disable Swap Files =========
set noswapfile
set nobackup
set nowb

" ========= Persistant Undo =========
" Keeps undo history across sessions by storing it in a file
if has("persistent_undo") && !isdirectory(expand('~').'/.vim/backups')
	silent !mkdir ~/.vim/backups > /dev/null 2>&1
	set undodir=~/.vim/backups
	set undofile
endif

" ========= Indentation =========
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

filetype plugin on
filetype indent on

"Display tabs and trailing spaces
set listchars=tab:▸\ ,eol:¬,trail:·

set nowrap "Don't wrap lines
set linebreak "Wrap lines at convenient points

" ========== Folding =========
set foldmethod=indent
set foldnestmax=3
set nofoldenable "Do not fold as default

" ========== Completion =========
set wildmode=list:longest
set wildmenu "Enables scrolling through matches with ctrl-n and ctrl-p
"Things to ignore when tab completing:
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

" ========= Scrolling ==========
set scrolloff=8 "Start scrolling 8 lines from margins
set sidescrolloff=15
set sidescroll=1

" ========== Search =========
set incsearch
set hlsearch
set ignorecase
set smartcase

" ========== Vim-Plug ==========
call plug#begin('~/.vim/plugged')

" ===== Navigation Plugins =====
Plug 'scrooloose/nerdtree' " File explorer
Plug 'ctrlpvim/ctrlp.vim' " Fuzzy finder for files, buffers, mrus, tags, ect.
Plug 'easymotion/vim-easymotion'

" ===== Display ===== 
Plug 'altercation/vim-colors-solarized' " Solarized colorscheme
Plug 'xuyuanp/nerdtree-git-plugin' " Displays Git status in NERDTree
Plug 'bling/vim-airline' " Displays a status / tabline
Plug 'airblade/vim-gitgutter' " Displays Git diff in the gutter
Plug 'nathanaelkane/vim-indent-guides' " ,ig toggles display of (i)ndent (g)uides
Plug 'elzr/vim-json' " Better highlighting for JSON

" ===== Text Editing Plugins =====
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'raimondi/delimitmate' " Auto pairs quotes, brackets, parens, ect.

Plug 'tpope/vim-fugitive' "Git wrapper

call plug#end()

" Easier escape sequence
inoremap jk <Esc>

set mouse=a " Enable mouse support

so ~/.vim/settings/keymap.vim
so ~/.vim/settings/keymap-mac.vim
so ~/.vim/settings/display.vim

